<?php
// app/Http/Controllers/BackupController.php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class BackupController extends Controller
{
    public function download()
    {
        $filename = 'db-backup-' . date('Y-m-d_H-i-s') . '.sql';

        return response()->streamDownload(function () {

            $dbName = env('DB_DATABASE');

            // ── Header ──────────────────────────────────────────────
            echo "-- Database Backup\n";
            echo "-- Date: " . date('Y-m-d H:i:s') . "\n";
            echo "-- Generated by BackupController\n\n";

            // ✅ Critical for Arabic / any non-ASCII text
            echo "SET NAMES utf8mb4;\n";
            echo "SET CHARACTER SET utf8mb4;\n";
            echo "SET character_set_connection = utf8mb4;\n";
            echo "SET FOREIGN_KEY_CHECKS = 0;\n\n";

            // ── Fetch all tables ─────────────────────────────────────
            $tables = DB::select("
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = ?
                  AND table_type = 'BASE TABLE'
                ORDER BY table_name
            ", [$dbName]);

            foreach ($tables as $tableRow) {

                $tableName = $tableRow->table_name ?? $tableRow->TABLE_NAME;

                echo "\n-- ========================================\n";
                echo "-- Table: `$tableName`\n";
                echo "-- ========================================\n";

                // DROP + CREATE
                $createResult = DB::select("SHOW CREATE TABLE `$tableName`")[0];
                $createSQL    = $createResult->{'Create Table'} ?? $createResult->{'create table'};

                echo "DROP TABLE IF EXISTS `$tableName`;\n";
                echo $createSQL . ";\n\n";

                // ── Detect primary key for stable chunking ───────────
                $pkRow = DB::select("
                    SELECT COLUMN_NAME
                    FROM information_schema.KEY_COLUMN_USAGE
                    WHERE TABLE_SCHEMA = ?
                      AND TABLE_NAME   = ?
                      AND CONSTRAINT_NAME = 'PRIMARY'
                    ORDER BY ORDINAL_POSITION
                    LIMIT 1
                ", [$dbName, $tableName]);

                $orderBy = $pkRow ? '`' . $pkRow[0]->COLUMN_NAME . '`' : DB::raw('1');

                // ── Dump rows in chunks of 500 ───────────────────────
                DB::table($tableName)
                    ->orderByRaw(is_string($orderBy) ? $orderBy : '1')
                    ->chunk(500, function ($rows) use ($tableName) {

                        foreach ($rows as $row) {

                            $values = [];

                            foreach ((array) $row as $value) {
                                if (is_null($value)) {
                                    $values[] = 'NULL';
                                } else {
                                    // ✅ mb-safe escaping — preserves Arabic & all Unicode
                                    $escaped  = str_replace(
                                        ["\\",  "'",   "\n",  "\r",  "\x1a"],
                                        ["\\\\", "\\'", "\\n", "\\r", "\\Z"],
                                        $value
                                    );
                                    $values[] = "'$escaped'";
                                }
                            }

                            echo "INSERT INTO `$tableName` VALUES ("
                                . implode(', ', $values)
                                . ");\n";
                        }
                    });

                echo "\n";
            }

            echo "\nSET FOREIGN_KEY_CHECKS = 1;\n";
            echo "-- Backup complete\n";

        }, $filename, [
            'Content-Type'        => 'application/octet-stream',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ]);
    }
}